id: A51C4F75F
base_file: f7C58.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:08:46.437186
  last_modified_at: 2022-06-17 11:08:46.437193
