id: A51C4F75F
base_file: fFE7F.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:08:46.549571
  last_modified_at: 2022-06-17 11:08:46.549576
