id: A51C4F75F
base_file: fE788.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:08:46.545201
  last_modified_at: 2022-06-17 11:08:46.545208
