id: A51C4F75F
base_file: f6287.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:08:46.432207
  last_modified_at: 2022-06-17 11:08:46.432217
