id: A51C4F75F
base_file: f6728.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:08:46.434882
  last_modified_at: 2022-06-17 11:08:46.434890
